### ISSUE TITLE
Multi Add to Cart implementation

### ISSUE THREAD

**Issue by ne0nlight** [gaiterjones/Magento2_AjaxButton#1]
First off, this is a great extension and exactly what we are looking for!

We have tried to get the implementation of the multi add to cart button to work, however the default hello world button just continues to load instead of the multi add to cart button (and we have cleared cache and did the setup:upgrade/compile/static-content refresh). We removed the .example from the layout xml so that should be loading correctly, and then within a CMS page, we have the following;

`
{{block class="Gaiterjones\AjaxButton\Block\AjaxButton" name="gj-ajaxbutton-addproductstocart" template="Gaiterjones_AjaxButton::ajaxbutton.phtml"}}
`

Are we missing something here that isn't pointing correctly to the add products to cart module of it?

Thanks for the help and insight!

**Comment by gaiterjones** [comment]
If you look at the example layouts, or the debug, you will see that you need extra arguments that tell the backend this is an add to cart button, and which product id's to add. If you don't specify any arguments you get the default 'hello world' example.

The layout for the multi add to cart looks like this

```
            <block class="Gaiterjones\AjaxButton\Block\AjaxButton" name="gj-ajaxbutton-addproductstocart" template="Gaiterjones_AjaxButton::ajaxbutton.phtml">
                <arguments>
                    <argument name="view_model" xsi:type="object">Gaiterjones\AjaxButton\ViewModel\AjaxButton</argument>
                    <argument name="ajaxbuttonid" xsi:type="string">3</argument>
                    <argument name="button_debug" xsi:type="boolean">true</argument>
                    <argument name="button_name" xsi:type="string">Multi Product Add To Cart Button</argument>
                    <argument name="button_class" xsi:type="string">product</argument>
                    <argument name="button_template" xsi:type="string">default</argument>
                    <argument name="action_template" xsi:type="string">addproductstocart</argument>
                    <argument name="action_data" xsi:type="array">
                        <item name="addtocart" xsi:type="boolean">true</item>
                        <item name="productids" xsi:type="string">2,3,4,5</item>
                    </argument>
                </arguments>
            </block>
```

You can see the extra arguments and also a data array with the product id's. I don't think you can add argument arrays in a cms block layout call, so you will need to create the block via layout or a template / block class

```
                $_ajaxButton = $this->getLayout()
                    ->createBlock(
                        "Gaiterjones\AjaxButton\Block\AjaxButton",
                        "gj-ajaxbutton1",
                        [
                            'data' => [
                                'button_name' => __('Add %1 Products to cart',$ProductCount),
                                'button_class' => 'product',
                                'button_template' => 'default',
                                'action_template' => 'addproductstocart',
                                'action_data' => [
                                    'addtocart' => true,
                                    'productids' => $ProductIds
                                ]
                            ]
                        ]
                    )
                    ->toHtml();

```

**Comment by ne0nlight** [comment]
Thanks for the help with my newbie questions!

I tried using a similar setup to what you had on a custom phtml file;

     /app/design/frontend/CleverSoft/core/Magento_Theme/templates/products.phtml

that I was loading in on a cms page;

    {{block class="Magento\Framework\View\Element\Template" template="Magento_Theme::products.phtml"}} 

however it didn't seem to be loading anything. The phtml file that was being called was filled with:

    <?php    
    $_ajaxButton = $this->getLayout()
                    ->createBlock(
                        "Gaiterjones\AjaxButton\Block\AjaxButton",
                        "gj-ajaxbutton1",
                        [
                            'data' => [
                                'button_name' => 'Add Products to cart',
                                'button_class' => 'product',
                                'button_template' => 'default',
                                'action_template' => 'addproductstocart',
                                'action_data' => [
                                    'addtocart' => true,
                                    'productids' => '123'
                                ]
                            ]
                        ]
                    )
                    ->toHtml();
    ?>


 I then tried adding the xml information to /app/design/frontend/CleverSoft/core/Magento_Theme/layout/default.xml like so;


    <referenceContainer name="content">
            <block name="customer.section.config" class="Magento\Customer\Block\SectionConfig"
                   template="Magento_Customer::js/section-config.phtml"/>
            <block name="customer.customer.data"
                   class="Magento\Customer\Block\CustomerData"
                   template="Magento_Customer::js/customer-data.phtml"/>
                   
    <block class="Gaiterjones\AjaxButton\Block\AjaxButton" name="gj-ajaxbutton-addproductstocart" template="Gaiterjones_AjaxButton::ajaxbutton.phtml">
                <arguments>
                    <argument name="ajaxbuttonid" xsi:type="string">3</argument>
                    <argument name="button_debug" xsi:type="boolean">true</argument>
                    <argument name="button_name" xsi:type="string">Multi Product Add To Cart Button!</argument>
                    <argument name="button_class" xsi:type="string">product</argument>
                    <argument name="button_template" xsi:type="string">default</argument>
                    <argument name="action_template" xsi:type="string">addproductstocart</argument>
                    <argument name="action_data" xsi:type="array">
                        <item name="addtocart" xsi:type="boolean">true</item>
                        <item name="productids" xsi:type="string">1429,419,2355</item>
                    </argument>
                </arguments>
            </block>
                   
        </referenceContainer>
`

Which displayed the block like expected and worked with adding the 3 products with one click, however the way it must be placed inside that xml, its actually showing up on all pages now. 

Is there anything glaringly obvious that i am messing up with the custom block that prevents the button from being created at all? Or is there a simple way I can have the introduced info into the xml only show when it's specifically called?

Thanks for all the help!!

**Comment by gaiterjones** [comment]
For it to display on specific product pages you will need a custom module, or some logic on the product page template to determine if the product qualifies for the button.
